version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: PostgresTaskMasterDB
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/
    networks:
      - my_network
volumes:
  postgres_db:
    driver: local

networks:
  my_network: